import React from "react";
import Link from "next/link";
import { Search, Plus, Eye } from "lucide-react";
const TC:Record<string,string>={New:"bg-slate-100 text-slate-600",Standard:"bg-blue-100 text-blue-700",Senior:"bg-purple-100 text-purple-700",Premium:"bg-amber-100 text-amber-700",Elite:"bg-red-100 text-red-700"};
const talents=[
  {id:"T-001",name:"พี่ก้อย",tier:"Premium",rating:4.9,trips:245,region:"กรุงเทพ",langs:"TH/EN/CN",status:"active"},
  {id:"T-002",name:"พี่เจมส์",tier:"Elite",rating:4.95,trips:380,region:"เชียงใหม่",langs:"TH/EN/JP",status:"active"},
  {id:"T-003",name:"พี่แนน",tier:"Senior",rating:4.7,trips:120,region:"ภูเก็ต",langs:"TH/EN",status:"active"},
  {id:"T-004",name:"พี่โอ๊ค",tier:"Standard",rating:4.5,trips:65,region:"กรุงเทพ",langs:"TH/EN/KR",status:"active"},
  {id:"T-005",name:"พี่มิ้นท์",tier:"Premium",rating:4.85,trips:290,region:"กรุงเทพ",langs:"TH/EN/FR",status:"active"},
  {id:"T-006",name:"พี่บอส",tier:"New",rating:4.2,trips:12,region:"กระบี่",langs:"TH/EN",status:"pending"},
];
export default function TalentListPage(){return(<div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-slate-900">👥 Talent Directory</h1></div><Link href="/talent-admin/talents/new" className="btn-primary text-sm flex items-center gap-1"><Plus className="w-4 h-4"/>เพิ่มไกด์</Link></div><div className="flex gap-2"><div className="relative flex-1"><Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2"/><input className="g-input w-full pl-9" placeholder="ค้นหา..."/></div><select className="g-input w-32"><option>ทุก Tier</option></select></div><div className="bg-white rounded-2xl border border-slate-200 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 border-b"><tr><th className="text-left px-4 py-3">ID</th><th className="text-left px-3 py-3">ชื่อ</th><th className="px-3 py-3">Tier</th><th className="px-3 py-3">Rating</th><th className="px-3 py-3">Trips</th><th className="px-3 py-3">พื้นที่</th><th className="px-3 py-3">ภาษา</th><th className="px-3 py-3">Status</th><th className="px-3 py-3"></th></tr></thead><tbody className="divide-y divide-slate-50">{talents.map(t=>(<tr key={t.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-mono text-xs text-primary">{t.id}</td><td className="px-3 py-3 font-medium">{t.name}</td><td className="px-3 py-3 text-center"><span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${TC[t.tier]}`}>{t.tier}</span></td><td className="px-3 py-3 text-center">⭐ {t.rating}</td><td className="px-3 py-3 text-center">{t.trips}</td><td className="px-3 py-3">{t.region}</td><td className="px-3 py-3 text-xs">{t.langs}</td><td className="px-3 py-3"><span className={`w-2 h-2 rounded-full inline-block ${t.status==="active"?"bg-emerald-400":"bg-amber-400"}`}/></td><td className="px-3 py-3"><Link href={`/talent-admin/talents/${t.id}`} className="text-primary text-xs"><Eye className="w-3.5 h-3.5"/></Link></td></tr>))}</tbody></table></div></div>);}
